services:
  postgres:
    image: postgres:15
    container_name: rewards-db
    environment:
      POSTGRES_DB: rewards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"